name: CI

on:
  push:

env:
  GOLANGCI_VERSION: "v1.54.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GO_VERSION:
          - "1.21"
          - "1.20"
          - "1.19"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.GO_VERSION }}

      - name: Test
        run: go list -f '{{.Dir}}' -m | xargs go test -v
